Add logging to gotip action
Signed-off-by: Yuri Shkuro <github@ysh.us>

diff --git a/.github/actions/setup-go-tip/action.yml b/.github/actions/setup-go-tip/action.yml
--- a/.github/actions/setup-go-tip/action.yml
+++ b/.github/actions/setup-go-tip/action.yml
@@ -8,11 +8,12 @@ runs:
       id: download
       shell: bash
       run: |
+        echo Download Go Tip
         set -euo pipefail
         tip=$(git ls-remote https://github.com/golang/go.git HEAD | awk '{print $1;}')
         echo "Go Tip version: ${tip}"
         retries=3
-        wait_time=3
+        wait_time=10
         success=false
         for ((i=1; i<=retries; i++)); do
           url="https://storage.googleapis.com/go-build-snap/go/linux-amd64/${tip}.tar.gz"
@@ -25,10 +26,12 @@ runs:
         done
         echo "success=${success}" >> $GITHUB_OUTPUT
 
-    - name: Install Go Tip
+    - name: Unpack gotip bundle
       if: steps.download.outputs.success == 'true'
       shell: bash
       run: |
+        echo Unpack gotip bundle
+        set -euo pipefail
         echo "Downloaded bundle:"
         ls -lah gotip.tar.gz
         export GOROOT="$HOME/sdk/gotip"
@@ -36,7 +39,9 @@ runs:
         tar -C $GOROOT -xzf gotip.tar.gz
         echo "GOROOT=$GOROOT" >> $GITHUB_ENV
 
-    - name: Install some Go version
+    # If download failed, we will try to build tip from source.
+    # This requires Go toolchain, so install it first.
+    - name: Install Go toolchain
       if: steps.download.outputs.success == 'false'
       uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
       with:
@@ -46,6 +51,8 @@ runs:
       if: steps.download.outputs.success == 'false'
       shell: bash
       run: |
+        echo Build Go Tip from source
+        set -euo pipefail
         go install golang.org/dl/gotip@latest
         gotip download
         export GOROOT="$(gotip env GOROOT)"
@@ -54,9 +61,11 @@ runs:
         # the go binary installed in previous step still takes precedence. So remove it.
         rm -f $(which go)
 
-    - name: Setup Go environemnt
+    - name: Setup Go environment
       shell: bash
       run: |
+        echo Setup Go environment
+        set -euo pipefail
         $GOROOT/bin/go version
         GOPATH="$HOME/gotip"
         PATH="$GOROOT/bin:$GOPATH/bin:$PATH"
@@ -66,9 +75,11 @@ runs:
     - name: Check Go Version
       shell: bash
       run: |
+        echo Check Go Version
+        set -euo pipefail
         echo "GOPATH=$GOPATH"
         echo "GOROOT=$GOROOT"
-        echo "which go"
+        echo "which go:"
         which -a go
         echo "Active Go version:"
         go version
